
# This file was generated by the {rix} R package on Sat Aug  5 16:49:45 2023
# It uses nixpkgs' revision 8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8 for reproducibility purposes
# which will install R version 4.2.2
# Report any issues to https://github.com/b-rodrigues/rix
    { pkgs ? import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/8ad5e8132c5dcf977e308e7bf5517cc6cc0bf7d8.tar.gz") {} }:

      with pkgs;

      let
      my-r = rWrapper.override {
        packages = with rPackages; [
          targets tarchetypes rmarkdown
          (buildRPackage {
    name = "housing";
    src = fetchgit {
      url = "https://github.com/rap4all/housing/";
      branchName = "fusen";
      rev = "1c860959310b80e67c41f7bbdc3e84cef00df18e";
      sha256 = "sha256-s4KGtfKQ7hL0sfDhGb4BpBpspfefBN6hf+XlslqyEn4=";
    };
    propagatedBuildInputs = [
        dplyr ggplot2 janitor purrr readxl rlang rvest stringr tidyr
      ];
  }) 
        ];
      };
      in
      mkShell {
        shellHook = ''
             Rscript -e "targets::tar_make()"
          '';
        LOCALE_ARCHIVE = "${glibcLocales}/lib/locale/locale-archive";
        buildInputs = [
          my-r
          ];
      }
